### ISSUE TITLE
Use ~/.aphorism for user added additions...

### ISSUE THREAD

**Issue by phallstrom** [katelovescode/aphorism#1]
Currently I have to edit your gem source to add stuff. This means if I update I'll lose those additions. Would be neat to have the gem check for ~/.aphorism and use that in addition to the defaults.

https://github.com/katelovescode/aphorism/blob/develop/README.md#add-more-aphorisms

**Comment by katelovescode** [comment]
FWIW this is the exact motivation for this gem because I hated digging into `fortune`'s backend deep in my system files to change some of the offensive stuff in there.  Great implementation suggestion, thanks.
